"""empty message

Revision ID: 1a6a3356f952
Revises: 
Create Date: 2026-03-16 13:13:37.953538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6a3356f952'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permission', sa.Column('permission_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'role_permission', 'permission', ['permission_id'], ['id'])
    op.drop_column('role_permission', 'permission')
    op.add_column('user_permission', sa.Column('permission_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_permission', 'permission', ['permission_id'], ['id'])
    op.drop_column('user_permission', 'permission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permission', sa.Column('permission', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_permission', type_='foreignkey')
    op.drop_column('user_permission', 'permission_id')
    op.add_column('role_permission', sa.Column('permission', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_column('role_permission', 'permission_id')
    # ### end Alembic commands ###
