"""add project specification table and stage kind

Revision ID: 074a657a4dde
Revises: b1c2d3e4f5a6
Create Date: 2026-09-17 22:36:09.809052

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "074a657a4dde"
down_revision: str | Sequence[str] | None = "b1c2d3e4f5a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_specification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("tasks", sa.JSON(), nullable=False),
        sa.Column("acceptance_criteria", sa.JSON(), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="draft", nullable=False),
        sa.Column("rejection_comment", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.add_column("project_stage", sa.Column("kind", sa.String(length=30), server_default="general", nullable=False))
    # ### end Alembic commands ###
    op.execute("UPDATE project_stage SET kind='spec_creation' WHERE name IN ('Создание ТЗ', 'Создание тз')")
    op.execute("UPDATE project_stage SET kind='spec_approval' WHERE name IN ('Техническое задание', 'Утверждение тз')")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "UPDATE project_stage SET kind='general' WHERE name IN ('Создание ТЗ', 'Создание тз', 'Техническое задание', 'Утверждение тз')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_stage", "kind")
    op.drop_table("project_specification")
    # ### end Alembic commands ###
