from __future__ import annotations

from unittest.mock import AsyncMock, Mock

import pytest

from src.core.exceptions import PermissionError
from src.model.user import Role
from src.model.workspace import WorkSpace
from src.repository.workspace_repository import WorkSpaceRepository
from src.schema.workspace import WorkSpaceCreate, WorkSpaceUpdate
from src.services.workspace_service import WorkSpaceService

# Константы для тестов
EXPECTED_WORKSPACES_COUNT = 2

MANAGER_ROLE = Role(id=4, name="manager")


class TestWorkSpaceService:
    """Тесты для WorkSpaceService"""

    @pytest.mark.asyncio
    async def test_should_create_workspace_with_valid_data(self):
        """Тест должен создать workspace с корректными данными"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_repository.add_participation = AsyncMock()
        mock_uow = Mock()
        mock_session = Mock()
        mock_result = Mock()
        mock_result.scalar_one_or_none.return_value = MANAGER_ROLE
        mock_session.execute = AsyncMock(return_value=mock_result)
        mock_uow.session = mock_session
        mock_repository.uow = mock_uow
        mock_workspace = WorkSpace(id=1, name="Test Workspace", author_id=1, status_id=1)
        mock_repository.create.return_value = mock_workspace

        workspace_service = WorkSpaceService(mock_repository)

        workspace_data = WorkSpaceCreate(name="Test Workspace", author_id=1, status_id=1)

        # when
        result = await workspace_service.create_workspace(workspace_data, author_id=1)

        # then
        assert result == mock_workspace
        mock_repository.create.assert_called_once_with(workspace_data)
        mock_repository.add_participation.assert_called_once_with(1, 1, MANAGER_ROLE.id)

    @pytest.mark.asyncio
    async def test_should_create_workspace_with_autogenerated_author_id(self):
        """Тест должен создать workspace с автогенерацией author_id"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_repository.add_participation = AsyncMock()
        mock_uow = Mock()
        mock_session = Mock()
        mock_result = Mock()
        mock_result.scalar_one_or_none.return_value = MANAGER_ROLE
        mock_session.execute = AsyncMock(return_value=mock_result)
        mock_uow.session = mock_session
        mock_repository.uow = mock_uow
        mock_workspace = WorkSpace(id=1, name="Test Workspace", author_id=1, status_id=1)
        mock_repository.create.return_value = mock_workspace

        workspace_service = WorkSpaceService(mock_repository)

        workspace_data = WorkSpaceCreate(name="Test Workspace")

        # when
        result = await workspace_service.create_workspace(workspace_data, author_id=1)

        # then
        assert result == mock_workspace
        assert workspace_data.author_id == 1
        mock_repository.create.assert_called_once_with(workspace_data)
        mock_repository.add_participation.assert_called_once_with(1, 1, MANAGER_ROLE.id)

    @pytest.mark.asyncio
    async def test_should_get_workspace_by_id(self):
        """Тест должен получить workspace по ID"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_workspace = WorkSpace(id=1, name="Test Workspace", author_id=1, status_id=1)
        mock_repository.get_by_id.return_value = mock_workspace

        workspace_service = WorkSpaceService(mock_repository)

        # when
        result = await workspace_service.get_workspace_by_id(1)

        # then
        assert result == mock_workspace
        mock_repository.get_by_id.assert_called_once_with(1)

    @pytest.mark.asyncio
    async def test_should_return_none_for_nonexistent_workspace(self):
        """Тест должен вернуть None для несуществующего workspace"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_repository.get_by_id.return_value = None

        workspace_service = WorkSpaceService(mock_repository)

        # when
        result = await workspace_service.get_workspace_by_id(999)

        # then
        assert result is None
        mock_repository.get_by_id.assert_called_once_with(999)

    @pytest.mark.asyncio
    async def test_should_update_workspace_with_valid_data(self):
        """Тест должен обновить workspace с корректными данными"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_workspace = WorkSpace(id=1, name="Test Workspace", author_id=1, status_id=1)
        mock_repository.get_by_id.return_value = mock_workspace

        updated_workspace = WorkSpace(id=1, name="Updated Workspace", author_id=1, status_id=1)
        mock_repository.update.return_value = updated_workspace

        workspace_service = WorkSpaceService(mock_repository)

        update_data = WorkSpaceUpdate(name="Updated Workspace", status_id=1)

        # when
        result = await workspace_service.update_workspace(1, update_data, current_user_id=1)

        # then
        assert result == updated_workspace
        mock_repository.get_by_id.assert_called_once_with(1)
        mock_repository.update.assert_called_once_with(1, update_data)

    @pytest.mark.asyncio
    async def test_should_return_none_when_updating_nonexistent_workspace(self):
        """Тест должен вернуть None при обновлении несуществующего workspace"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_repository.get_by_id.return_value = None

        workspace_service = WorkSpaceService(mock_repository)

        update_data = WorkSpaceUpdate(name="Updated Workspace")

        # when
        result = await workspace_service.update_workspace(999, update_data, current_user_id=1)

        # then
        assert result is None
        mock_repository.get_by_id.assert_called_once_with(999)

    @pytest.mark.asyncio
    async def test_should_raise_permission_error_when_updating_workspace_not_as_author(self):
        """Тест должен выбросить PermissionError при обновлении не автором"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_workspace = WorkSpace(id=1, name="Test Workspace", author_id=1, status_id=1)
        mock_repository.get_by_id.return_value = mock_workspace

        workspace_service = WorkSpaceService(mock_repository)

        update_data = WorkSpaceUpdate(name="Updated Workspace")

        # when & then
        with pytest.raises(PermissionError, match="Only workspace author can update workspace"):
            await workspace_service.update_workspace(1, update_data, current_user_id=999)

    @pytest.mark.asyncio
    async def test_should_delete_workspace_successfully(self):
        """Тест должен успешно удалить workspace"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_workspace = WorkSpace(id=1, name="Test Workspace", author_id=1, status_id=1)
        mock_repository.get_by_id.return_value = mock_workspace
        mock_repository.delete.return_value = True

        workspace_service = WorkSpaceService(mock_repository)

        # when
        result = await workspace_service.delete_workspace(1, current_user_id=1)

        # then
        assert result is True
        mock_repository.get_by_id.assert_called_once_with(1)
        mock_repository.delete.assert_called_once_with(1)

    @pytest.mark.asyncio
    async def test_should_return_false_when_deleting_nonexistent_workspace(self):
        """Тест должен вернуть False при удалении несуществующего workspace"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_repository.get_by_id.return_value = None

        workspace_service = WorkSpaceService(mock_repository)

        # when
        result = await workspace_service.delete_workspace(999, current_user_id=1)

        # then
        assert result is False
        mock_repository.get_by_id.assert_called_once_with(999)

    @pytest.mark.asyncio
    async def test_should_raise_permission_error_when_deleting_workspace_not_as_author(self):
        """Тест должен выбросить PermissionError при удалении не автором"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_workspace = WorkSpace(id=1, name="Test Workspace", author_id=1, status_id=1)
        mock_repository.get_by_id.return_value = mock_workspace

        workspace_service = WorkSpaceService(mock_repository)

        # when & then
        with pytest.raises(PermissionError, match="Only workspace author can delete workspace"):
            await workspace_service.delete_workspace(1, current_user_id=999)

    @pytest.mark.asyncio
    async def test_should_get_workspaces_by_author(self):
        """Тест должен получить workspace по автору"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_workspaces = [
            WorkSpace(id=1, name="Workspace 1", author_id=1, status_id=1),
            WorkSpace(id=2, name="Workspace 2", author_id=1, status_id=1),
        ]
        mock_repository.get_by_author_id.return_value = mock_workspaces

        workspace_service = WorkSpaceService(mock_repository)

        # when
        result = await workspace_service.get_workspaces_by_author(1)

        # then
        assert result == mock_workspaces
        assert len(result) == EXPECTED_WORKSPACES_COUNT
        mock_repository.get_by_author_id.assert_called_once_with(1)

    @pytest.mark.asyncio
    async def test_should_get_workspaces_by_status(self):
        """Тест должен получить workspace по статусу"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_workspaces = [
            WorkSpace(id=1, name="Workspace 1", author_id=1, status_id=1),
            WorkSpace(id=2, name="Workspace 2", author_id=2, status_id=1),
        ]
        mock_repository.get_by_status_id.return_value = mock_workspaces

        workspace_service = WorkSpaceService(mock_repository)

        # when
        result = await workspace_service.get_workspaces_by_status(1)

        # then
        assert result == mock_workspaces
        assert len(result) == EXPECTED_WORKSPACES_COUNT
        mock_repository.get_by_status_id.assert_called_once_with(1)

    @pytest.mark.asyncio
    async def test_should_get_workspaces_paginated(self):
        """Тест должен получить workspace с пагинацией"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_workspaces = [
            WorkSpace(id=1, name="Workspace 1", author_id=1, status_id=1),
            WorkSpace(id=2, name="Workspace 2", author_id=2, status_id=1),
        ]
        mock_repository.get_multi.return_value = mock_workspaces
        mock_repository.count.return_value = 2

        workspace_service = WorkSpaceService(mock_repository)

        # when
        workspaces, total = await workspace_service.get_workspaces_paginated(page=1, limit=10)

        # then
        assert workspaces == mock_workspaces
        assert total == EXPECTED_WORKSPACES_COUNT
        assert len(workspaces) == EXPECTED_WORKSPACES_COUNT
        mock_repository.get_multi.assert_called_once_with(skip=0, limit=10)
        mock_repository.count.assert_called_once()

    @pytest.mark.asyncio
    async def test_should_calculate_correct_skip_for_pagination(self):
        """Тест должен корректно рассчитать skip для пагинации"""
        # given
        mock_repository = Mock(spec=WorkSpaceRepository)
        mock_repository.get_multi.return_value = []
        mock_repository.count.return_value = 0

        workspace_service = WorkSpaceService(mock_repository)

        # when
        await workspace_service.get_workspaces_paginated(page=3, limit=10)

        # then
        mock_repository.get_multi.assert_called_once_with(skip=20, limit=10)
