# Общие экспорты схем из всех модулей
from __future__ import annotations

from .auth import Token
from .base import Blank, DeleteResponse, FindBase, FindDateRange, FindResult, PaginatedResponse
from .kanban import (
    ColumnBase,
    ColumnCreate,
    ColumnListResponse,
    ColumnResponse,
    ColumnUpdate,
    ColumnWithTasksAndSubtasksResponse,
    ProjectBoardResponse,
    SubtaskBase,
    SubtaskCreate,
    SubtaskListResponse,
    SubtaskReorder,
    SubtaskResponse,
    SubtaskUpdate,
    TaskBase,
    TaskCreate,
    TaskFilter,
    TaskHistoryResponse,
    TaskListResponse,
    TaskMove,
    TaskPriority,
    TaskReorder,
    TaskResponse,
    TaskUpdate,
)
from .project import ProjectCreate, ProjectFull, ProjectListItem, ProjectListResponse, ProjectResponse, ProjectUpdate
from .resume import ResumeCreate, ResumeFull, ResumeListResponse, ResumeResponse, ResumeUpdate
from .user import UserBase, UserCreate, UserFull, UserListItem, UserListResponse, UserResponse, UserUpdate

__all__ = [
    "Blank",
    "ColumnBase",
    "ColumnCreate",
    "ColumnListResponse",
    "ColumnResponse",
    "ColumnUpdate",
    "ColumnWithTasksAndSubtasksResponse",
    "DeleteResponse",
    "FindBase",
    "FindDateRange",
    "FindResult",
    "PaginatedResponse",
    "ProjectBoardResponse",
    "ProjectCreate",
    "ProjectFull",
    "ProjectListItem",
    "ProjectListResponse",
    "ProjectResponse",
    "ProjectUpdate",
    "ResumeCreate",
    "ResumeFull",
    "ResumeListResponse",
    "ResumeResponse",
    "ResumeUpdate",
    "SubtaskBase",
    "SubtaskCreate",
    "SubtaskListResponse",
    "SubtaskReorder",
    "SubtaskResponse",
    "SubtaskUpdate",
    "TaskBase",
    "TaskCreate",
    "TaskFilter",
    "TaskHistoryResponse",
    "TaskListResponse",
    "TaskMove",
    "TaskPriority",
    "TaskReorder",
    "TaskResponse",
    "TaskUpdate",
    "Token",
    "UserBase",
    "UserCreate",
    "UserFull",
    "UserListItem",
    "UserListResponse",
    "UserResponse",
    "UserUpdate",
]
